# ============================================================================
# file: docker-compose.yml
# Description: Docker Compose configuration for Wazuh Agent with dynamic .env injection.
# ============================================================================

services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.6
    container_name: wazuh-agent
    restart: always
    environment:
      - WAZUH_MANAGER_IP=${WAZUH_MANAGER_IP:-127.0.0.1}
      - WAZUH_MANAGER_PORT=${WAZUH_MANAGER_PORT:-1514}
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-template/ossec.conf:ro
