# ============================================================================
# file: fluent-bit.conf
# description: configuration file for fluent-bit client logs forward to Grafana Loki and Wazuh Manager
# ============================================================================

# ====== SERVICE ======
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

# ====== INPUT ======
# auth.log: authentication logs
[INPUT]
    Name             tail
    Path             /var/log/auth.log
    Tag              client.auth
    DB               /fluent-bit/db/auth_logs.db
    Buffer_Max_Size  5MB
    Mem_Buf_Limit    50MB
    Skip_Long_Lines  On

# nginx/access.log: web logs
# [INPUT]
#     Name             tail
#     Path             /var/log/nginx/access.log
#     Parser           nginx
#     Tag              client.nginx
#     DB               /fluent-bit/db/nginx_logs.db
#     Buffer_Max_Size  5MB
#     Mem_Buf_Limit    50MB
#     Skip_Long_Lines  On

# ====== FILTER ======
# Inject static tags/metadata into the records
[FILTER]
    Name             record_modifier
    Match            *
    Record           hostname ${CLIENT_HOSTNAME}
    Record           environment ${ENV}
    Record           agent_type fluent-bit-client

# ====== OUTPUT ======
# Output to Grafana Loki (Encrypted TLS & HTTP Auth)
[OUTPUT]
    Name             loki
    Match            client.auth
    Host             ${LOKI_HOST}
    Port             ${LOKI_PORT}
    Labels           job=auth, hostname=${CLIENT_HOSTNAME}, env=${ENV}
    Line_Format      json
    header           X-Scope-OrgID tenant1
    tenant_id        ${LOKI_TENANT_ID:-tenant1}
    tls              ${ENABLE_TLS}
    tls.verify       ${TLS_VERIFY}
    tls.ca_file      /fluent-bit/certs/ca.crt
    http_user        ${LOKI_USER}
    http_passwd      ${LOKI_PASSWORD}

# Output to Wazuh Manager (via Syslog TCP/TLS)
# [OUTPUT]
#     Name                    syslog
#     Match                   *
#     Host                    ${WAZUH_HOST}
#     Port                    ${WAZUH_PORT}
#     Mode                    tcp
#     Syslog_Format           rfc3164
#     syslog_appname_preset   lsmp-client
#     syslog_hostname_preset  ${CLIENT_HOSTNAME}
#     syslog_message_key      log
#     tls                     ${ENABLE_TLS}
#     tls.verify              ${TLS_VERIFY}
#     tls.ca_file             /fluent-bit/certs/ca.crt
