# ============================================================================
# file: parsers.conf
# description: Paesers configuration file for fluent-bit on the wazuh server
# ============================================================================

# ====== PARSERS - Wazuh Alerts ======
[PARSER]
    Name        json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
